name: CI

on:
  workflow_dispatch:

jobs:
  Job-Install-Tools:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Current repository
        uses: actions/checkout@v2

      - name: Install Python with Specific(3.8)
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your desired Python version

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli      
  
  Job-Verify:
    runs-on: ubuntu-latest
    needs: Job-Install-Tools

    steps:
      - name: Clone Current repository
        uses: actions/checkout@v2
      - name: Verify Python Version
        run: python --version
      - name: Verify PIP
        run: pip --version
      - name: List of PIP Packages Installed
        run: pip list
      - name: Verify AWS CLI
        run: aws --version
  
  Job-Configure-AWS-CLI:
    runs-on: ubuntu-latest
    needs: Job-Verify

    steps:
      - name: Clone Current repository
        uses: actions/checkout@v2

      - name: Install dependencies using requirements.txt file
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ML Comparison
        run: python compare_models.py
      
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: model_comparisons
          path: model_comparisons.csv
  